version: "3.7"
services:
    php:
        image: serversideup/php:8.1-fpm-nginx
        volumes:
            - .:/var/www/html/
        environment:
            AUTORUN_ENABLED: false
        ports:
            - 80:80
            - 443:443
        depends_on:
            - "mariadb"
        networks:
            - laravel-app_default

    mariadb:
        image: mariadb:10.5.6
        container_name: mariadb
        hostname: "laravel_mariadb"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 3306:3306
        networks:
            - laravel-app_default

    meilisearch:
        image: getmeili/meilisearch:v0.27.2
        networks:
            - laravel-app_default
        hostname: "laravel-docker_meilisearch"
        environment:
            MEILI_NO_ANALYTICS: "true"
        volumes:
            - ./docker/meilisearch/meilisearch_data:/meili_data:cached
        depends_on:
            - "mariadb"
            - "php"

    # nginx:
    #     image: nginx:1.23.3
    #     container_name: nginx
    #     hostname: "laravel_nginx"
    #     restart: unless-stopped
    #     ports:
    #         - 8180:80
    #         - 8143:443
    #     volumes:
    #         - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    #         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - php
    #     networks:
    #         - laravel-app_default

    redis:
        image: redis:6
        container_name: redis
        hostname: "laravel_redis"
        restart: unless-stopped
        volumes:
            - ./docker/redis/data:/data:cached
        depends_on:
            - "mariadb"
            - "php"
        command: "redis-server --appendonly yes --requirepass redispassword"
        networks:
            - laravel-app_default

networks:
    laravel-app_default:
        driver: bridge
