version: "3.7"
services:
    php:
        image: serversideup/php:8.1-fpm-nginx
        container_name: php
        hostname: laravel_php
        restart: unless-stopped
        volumes:
            - .:/var/www/html/
        environment:
            AUTORUN_ENABLED: false
        ports:
            - 80:80
            - 443:443
        depends_on:
            - mariadb
            - meilisearch
            - redis
            - mailpit
            - selenium
        networks:
            - laravel-app_default

    mariadb:
        image: mariadb:10.5.6
        container_name: mariadb
        hostname: "laravel_mariadb"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 3306:3306
        networks:
            - laravel-app_default

    meilisearch:
        image: getmeili/meilisearch:v0.27.2
        container_name: meilisearch
        hostname: laravel_meilisearch
        restart: unless-stopped
        environment:
            MEILI_NO_ANALYTICS: "true"
        volumes:
            - ./docker/meilisearch/meilisearch_data:/meili_data:cached
        ports:
            - 7700:7700
        networks:
            - laravel-app_default

    redis:
        image: redis:6
        container_name: redis
        hostname: "laravel_redis"
        restart: unless-stopped
        volumes:
            - ./docker/redis/data:/data:cached
        ports:
            - 6379:6379
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        networks:
            - laravel-app_default

    mailpit:
        image: "axllent/mailpit:latest"
        container_name: mailpit
        hostname: "laravel_mailpit"
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - laravel-app_default

    selenium:
        image: seleniarm/standalone-chromium
        container_name: selenium
        hostname: "laravel_selenium"
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - "/dev/shm:/dev/shm"
        networks:
            - laravel-app_default

networks:
    laravel-app_default:
        driver: bridge
